### ISSUE TITLE
only the 0,25 tSIT reward did get trough, missing the 1,75 tSIT reward? [BUG]

### ISSUE THREAD

**Issue by abspoel99** [silicoin-network/silicoin-blockchain#53]
Not sure if this is a BUG, but reward is only 0,25 tSIT for winning a block.

started the new silicoin miner (v0.09) with a clean install, and succesfully conected to the new blockchain. (Network name: testnet)

Won my first block on this chain a hour ago and won 0,25 tSIT instead of 0,25 + 1,75. Checked my wallet payout adesses and these are set correct in the GUI.

Checked the config file and confirmed the correct walet adress (same as in GUI).

![image](https://user-images.githubusercontent.com/29400615/125614731-acfc5f94-347a-436e-b775-4874b0b443d3.png)

**Comment by qLutCh55** [comment]
Do you have any poolable plots or are they all OG plots?

**Comment by abspoel99** [comment]
have a mix of poolable plots and OG plots atm. 

won a second block with no issues so far, (see screenshot) will investigate in to it further tomorrow

![image](https://user-images.githubusercontent.com/29400615/125703903-43426611-d2ca-4d03-9272-ec117c0a1c12.png)

**Comment by qLutCh55** [comment]
So I have a theory, and I might be wrong. I installed the latest version on ubuntu server - cli only. The version is 0.0.8, the node synced, and everything is working BUT I noticed in the cli for silicoin - it has the plotnft command is which has to do with the pooling setup in chia. So I got a feeling one of your poolable plots won a block - but because it was a pool plot, you got 0.25 reward for being the block winner, and 1.75 went to the pool... which in this case either is completely lost since you did not have a pool setup - or its possibly sent to the pool address setup on your chia. So they might have it, or completely discard it since they are only working with chia. 

I thought I would combat this by setting up a solo (local) pool, so that if my pooling plots win -I get the 0.25 as a reward, but then the rest of the 1.75 would go to my solo pool wallet. The 2 issues with this right now - GUI doesn't have this functionality, but you might have it over powershell (to create pool). The other issue is, even though I created a solo pool, the contract address is different to that of my chia pool contract adress which is used right not to plot my poolable plots. So I got a feeling once again, that my 1.75 reward for a poolable plot will be sent to that pool (space.pool) and they will disregard it since it isn't chia... 

I don't know how farming poolable plots will work with different crypto's like silicoin or flax. Will one have to find a pool that does all of them (or most) - so you dont loose out on rewards....

**Comment by Kanal003** [comment]
the issue is across all forks of chia other than the original chia... the OG plots prior to pool will award all of the reward for finding a block/ however the pool plots will only reward 1\8th of the reward and the other 7\8th will not be rewarded because the plots do not specify an address for them to go to when not pool farming

**Comment by Kanal003** [comment]
> I thought I would combat this by setting up a solo (local) pool, so that if my pooling plots win - I get the 0.25 as a reward, but then the rest of the 1.75 would go to my solo pool wallet. The 2 issues with this right now - GUI doesn't have this functionality, but you might have it over powershell (to create pool). 

let me know if your workaround works and how you set it up

**Comment by qLutCh55** [comment]
So no luck yet.

But at this stage, I fear that farming other coins with poolable plots are just not going to work. Even though I created a new plotnft with silicoin, the contract address needed to create a poolable plot is different from the chia plotnft contract address, so I won't be able to claim the other 1.75 even though it is a solo pool. Eg.

CHIA PLOTNFT:

Wallet height: 583487
Sync status: Synced
Wallet id 2: 
Current state: FARMING_TO_POOL
Current state from block height: 551879
Launcher ID: 4571axxxx
Target address (not for plotting): xch19ukfxxxx
Owner public key: aa67dfxxxx
P2 singleton address (pool contract address for plotting): xch1deeuxxxx
Current pool URL: https://eu1.pool.space
Current difficulty: 6
Points balance: 220
Relative lock height: 64 blocks
Payout instructions (pool will pay to this address): xch1y9xxxxx


SILICOIN PLOTNFT:

Wallet height: 25467
Sync status: Synced
Wallet id 2: 
Current state: SELF_POOLING
Current state from block height: 13115
Launcher ID: 4800c7xxxx
Target address (not for plotting): tsit1qmxxxx
Owner public key: aa67dfxxxxx
P2 singleton address (pool contract address for plotting): tsit19jxxxx
Claimable balance: 0.0 tsit (0 mojo)


The only variable that is the same in both cases is the owner public key - but that is not used in the plot creation process.

I think flax coin raised a similar issue with chia devs - but couldn't find much clarity in the answers.
https://github.com/Chia-Network/chia-blockchain/issues/7134

I dont know if starting a public pool, that will allow you to farm multiple coins is the answer... or if its even possible.

**Comment by zo8031** [comment]
I have the same problem, I got 0.25 instead of 2, is there any fix to this issue?

**Comment by jacklwm90** [comment]
same issue here, won 2 block and gotten only 0.25 each, my plots are mostly poolable plots

**Comment by abspoel99** [comment]
Apparently the NFT plots wontt work with the software front the fork. At chia they made it so that there isn't a simpele copy and paste solution the

Outlook voor Android<https://aka.ms/AAb9ysg> downloaden

________________________________

**Comment by MangoLi09** [comment]
same issue here, won 2 block and gotten only 0.25 each, my plots are og and poolable plots mix

**Comment by ljudov** [comment]
Same issue. There is no way that this has to do something with poolable ploots. I'm farming other forks as well, happened only on silicoin.

**Comment by albertcoady** [comment]
Upgrade to 0.2.1 and you can claim your missing tSIT
